

function [fpRate, numViolations] = ISIViolations(spikeTrain, minISI, refDur)
% computes an estimated false positive rate of the spikes in the given
% spike train. You probably don't want this to be greater than a few
% percent of the spikes. 
%
% - minISI [sec] = minimum *possible* ISI (based on your cutoff window); likely 1ms
% or so. It's important that you have this number right.
% - refDur [sec] = estimate of the duration of the refractory period; suggested value = 0.002.
% It's also important that you have this number right, but there's no way
% to know... also, if it's a fast spiking cell, you could use a smaller
% value than for regular spiking.
%
% This function was updated on 2023-09-05 by NS to reflect a correction.
% There were two problems: 
% 1) The approximation previously used, which was chosen to avoid getting
% imaginary results, wasn't accurate to the Hill et al paper on which this
% method was based, nor was it accurate to the correct solution to the
% problem
% 2) Hill et al did not have the correct solution to the problem. The Hill
% paper used an expression derived from an earlier work (Meunier et al
% 2003) which had assumed a special case: the "contamination" was itself
% only generated by a single neuron and therefore the contaminating spikes
% themselves had a refractory period. If instead the contaminating spikes
% are generated from a real poisson process (as in the case of electrical
% noise or many nearby neurons generating the contamination), then the
% correct expression is different, as now calculated here. This expression
% is given in Llobet et al. bioRxiv 2022
% (https://www.biorxiv.org/content/10.1101/2022.02.08.479192v1.full.pdf)
%
% In practice, the three methods (the real Hill equation, the method
% previously implemented here, and the correct equation as now implemented)
% return almost identical values for contamination less than ~20%. They
% diverge strongly for 30% or more. 
%
% Bonus: the correct expression no longer returns imaginary values!

warning('sortingQuality:ISIViolations -- The behavior of this function has changed!! as of 2023-09-05. The fix should make only minor changes to the results. Please see function comments for details.')

Nt = length(spikeTrain); % total spike count
D = max(spikeTrain); % duration of recording
isis = diff(spikeTrain);
numViolations = sum(isis <= refDur & isis>minISI); % number of observed violations

fpRate =  1 - sqrt(1 - numViolations*D/(Nt^2*(refDur-minISI)));

end

%{ 
% everything below is the old behavior of this function. 


totalRate = length(spikeTrain)/spikeTrain(end);
numViolations = sum(diff(spikeTrain) <= refDur);

% Spikes occurring under the minimum ISI are by definition false positives;
% their total rate relative to the rate of the neuron overall gives the
% estimated false positive rate.
% NOTE: This does not use the equation from Dan Hill's paper (see below)
% but instead uses the equation from his UltraMegaSort
violationTime = 2*length(spikeTrain)*(refDur-minISI); % total time available for violations - 
                                                    % there is an available
                                                    % window of length
                                                    % (refDur-minISI) after
                                                    % each spike.
violationRate = numViolations/violationTime;
fpRate = violationRate/totalRate;

if fpRate>1
    % it is nonsense to have a rate >1, however having such large rates
    % does tell you something interesting, namely that the assumptions of
    % this analysis are failing!
    fpRate = 1; 
end


% Here is with Dan Hill's equation (J. Neurosci, 2012)
%  NOTE: actually, this method will return imaginary results for large-ish
%  numbers of violations. 
% tauR = refDur;
% tauC = minISI;
% T = spikeTrain(end);
% N = length(spikeTrain);
% R = sum(diff(spikeTrain) <= tauR);
% 
% k = 2*(tauR-tauC)*N^2;
% rts = roots([k -k R*T]);
% 
% fpRate = min(rts);
% numViolations = R;
end
%}